name: Public Admin

on:
  push:
    branches: [main]

jobs:
  Server:
    runs-on: ubuntu-latest
    name: "publish Server"
    environment: npm
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Set Pnpm Registry
        run: pnpm config set registry https://registry.npm.taobao.org/
      - name: Install modules
        run: cd packages/server && pnpm install --lockfile-only
      - name: Build
        run: cd packages/server && pnpm run build
      - name: Deploy to Aliyun
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avzr --delete"
          SOURCE: "packages/server/dist"
          REMOTE_HOST: "47.98.252.43"
          REMOTE_USER: "root"
          TARGET: "/root/source/react-arco-admin/packages/server"
  Admin:
    runs-on: ubuntu-latest
    name: "publish Admin"
    environment: npm

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: cd packages/admin && pnpm install
      - name: Build
        run: cd packages/admin && pnpm run build
      - name: Deploy to Aliyun
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avzr --delete"
          SOURCE: "packages/admin/dist"
          REMOTE_HOST: "47.98.252.43"
          REMOTE_USER: "root"
          TARGET: "/root/source/react-arco-admin/packages/admin"
